{application,earmark,
             [{applications,[kernel,stdlib,elixir,earmark_parser]},
              {description,"Earmark is a pure-Elixir Markdown converter.\n\nIt is intended to be used as a library (just call Earmark.as_html),\nbut can also be used as a command-line tool (run mix escript.build\nfirst).\n\nOutput generation is pluggable.\n"},
              {modules,['Elixir.Earmark','Elixir.Earmark.AstTools',
                        'Elixir.Earmark.Cli',
                        'Elixir.Earmark.Cli.Implementation',
                        'Elixir.Earmark.Error','Elixir.Earmark.Helpers',
                        'Elixir.Earmark.Message','Elixir.Earmark.Options',
                        'Elixir.Earmark.SysInterface',
                        'Elixir.Earmark.SysInterface.Behavior',
                        'Elixir.Earmark.SysInterface.Implementation',
                        'Elixir.Earmark.TagSpecificProcessors',
                        'Elixir.Earmark.Transform']},
              {registered,[]},
              {vsn,"1.4.16"}]}.
